version: '2'
services:
  jenkins:
    build: .
    ports:
    - '6080:8080'
    - '50000:50000'
    volumes:
    - 'jenkins_home:/var/jenkins_home'
    environment:
      LDAP_SERVER: 'openldap-serv.com:389'
      LDAP_ROOTDN: 'dc=openldap-serv,dc=com'
#      LDAP_INHIBIT_INFER_ROOTDN (required if LDAP_ROOTDN is empty), flag indicating if ROOT_DN should be infered
#      LDAP_USER_SEARCH_BASE (optional), base organization unit to use to search for users
#      LDAP_USER_SEARCH (optional), LDAP object field to use for the search query
#      LDAP_GROUP_SEARCH_BASE (optional), base organization unit to use to search for groups
#      LDAP_GROUP_SEARCH_FILTER (optional), filter to use querying for groups
#      LDAP_GROUP_MEMBERSHIP_STRATEGY='FromUserRecordLDAPGroupMembershipStrategy' #FromGroupSearchLDAPGroupMembershipStrategy
#      LDAP_GROUP_MEMBERSHIP_SEARCH_FILTER (optional), filter to use when writing queries to verify if a user is member of a group, used when LDAP_GROUP_MEMBERSHIP_STRATEGY is FromGroupSearchLDAPGroupMembershipStrategy
#      LDAP_USER_RECORD_ATTRIBUTE_NAME (optional), the attribute name that is used to determine the groups to which a user belongs, used when LDAP_GROUP_MEMBERSHIP_STRATEGY is FromUserRecordLDAPGroupMembershipStrategy
      LDAP_MANAGER_DN: admin
      LDAP_MANAGER_PASSWORD: admin
#      LDAP_INHIBIT_INFER_ROOTDN (required), flag indicating if ROOT_DN should be infered
#      LDAP_DISPLAY_NAME_ATTRIBUTE_NAME (optional), LDAP object field used as a display name
#      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER (required), flag indicating if the email address resolver should be disabled
#      LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME (optional), LDAP object field used as a email address
#      LDAP_GROUP_NAME_ADMIN (optional), LDAP admin group. Default to administrators.
      JENKINS_ADMIN_LOGIN: admin
      JENKINS_ADMIN_PASSWORD: admin
volumes:
  jenkins_home:
    driver: local
