#curl -X POST -H "Content-Type: application/json" http://localhost:8080/api/login_check -d '{"username":"yassin.helali@gmail.com","password":"blabla.."}' 
login_check:
    path: /api/login_check
    methods:  [POST]
